version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - vet
    - dupl
    - goconst
    - gocyclo
    - goheader
    - prealloc
    - revive
    - unconvert
    - unparam

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable-all: true
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 150
  goheader:
    template-file: .golangci.header
  revive:
    rules:
      - name: var-naming
      - name: package-comments
      - name: exported
      - name: context-as-utility
  unparam:
    check-called-before-shadowed: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 10
