

services:
  allstar-nexus:
    build:
      context: .
      dockerfile: Dockerfile
    image: allstar-nexus:latest
    container_name: allstar-nexus
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      # Mount data directory for persistence (astdb, database, config)
      - ./data:/app/data
      # Optional: mount custom config file
      - ./config.yaml:/app/data/config.yaml:ro
    environment:
      # Application settings
      - PORT=8080
      - APP_ENV=production

      # Database
      - DB_PATH=/app/data/allstar.db
      - ASTDB_PATH=/app/data/astdb.txt

      # Security (CHANGE THESE!)
      - JWT_SECRET=change-me-in-production

      # AMI Connection (configure for your Asterisk server)
      - AMI_ENABLED=true
      #- AMI_HOST=127.0.0.1
      #- AMI_PORT=5038
      #- AMI_USERNAME=admin
      #- AMI_PASSWORD=change-me

      # Node Configuration (comma-separated list or set in config.yaml)
      # - NODES=[594950,43732]

      # Feature Toggles
      - ALLOW_ANON_DASHBOARD=true
      - DISABLE_LINK_POLLER=false

    # Optional: if AMI server is on host network
    # network_mode: host

    # Health check
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Resource limits (optional)
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 512M
    #     reservations:
    #       cpus: '0.5'
    #       memory: 256M

# Optional: named volume instead of bind mount
# volumes:
#   allstar-data:
