name: CI

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend deps
        working-directory: frontend
        run: npm ci

      - name: Frontend build (Vite)
        working-directory: frontend
        run: npm run build

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Go Test
        run: go test ./...

      - name: Go Build
        run: go build -ldflags "-X 'main.buildVersion=${{ github.sha }}' -X 'main.buildTime=$(date -u +"%Y-%m-%dT%H:%M:%SZ")'" -o allstar-nexus .
