name: E2E (manual)

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to run'
        required: false
        default: 'chromium'
      run_build:
        description: 'Build frontend before tests'
        required: false
        default: 'true'

jobs:
  playwright-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend deps
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        if: ${{ inputs.run_build == 'true' }}
        working-directory: frontend
        run: npm run build

      - name: Install Playwright Browsers
        working-directory: frontend
        run: npx playwright install --with-deps ${{ inputs.browser }}

      - name: Run Playwright E2E
        working-directory: frontend
        env:
          CI: "true"
        run: |
          npx playwright test --project=${{ inputs.browser }}

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report/
          if-no-files-found: ignore

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: frontend/test-results/
          if-no-files-found: ignore
